apiVersion: v2
name: glasnosticd
description: Glasnostic Kubernetes Dataplane
type: application
version: 0.1.1
appVersion: "1.0.0"

home: https://github.com/glasnostic/helm-charts
icon: https://raw.githubusercontent.com/glasnostic/helm-charts/master/docs/logo/glasnostic.png
sources:
  - https://github.com/glasnostic/helm-charts
maintainers:
  - email: christoph@glasnostic.com
    name: Christoph Kassen
keywords:
  - glasnostic
  - kubernetes
  - helm
