apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "glasnostic.fullname" . }}
data:
  NETWORK_KEY: {{ required "You must set a valid Glasnostic Network ID API key" .Values.networkKey | quote }}
  IGNORE_PASSTHROUGH_REPORT: "true"
