apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "glasnosticd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "glasnosticd.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "glasnosticd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/webhook.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "glasnosticd.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "glasnosticd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: injection-secret
          secret:
            secretName: injection-secret
            optional: false
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "glasnosticd.fullname" . }}-config
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: INJECT_CERT_PATH
              value: "/etc/glasnostic/tls.crt"
            - name: INJECT_KEY_PATH
              value: "/etc/glasnostic/tls.key"
            - name: SIDECAR_IMAGE
              value: "{{ .Values.sidecar.repository }}:{{ .Values.sidecar.tag }}"
            - name: NODE_PORT
              value: {{ .Values.nodePort | quote }}
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            - name: exchange
              containerPort: 40753
              hostPort: {{ .Values.nodePort }}
            - name: service-port
              containerPort: 9091
              hostPort: 9091
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/etc/glasnostic"
              name: injection-secret
              readOnly: true
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
