#Create namespace via Helm to ensure injector does not interfere with the glasnosticd containers
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    glasnostic: disable