---
# rbac role definition
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: glasnosticd
rules:
  - apiGroups: ["", "coordination.k8s.io"]
    resources: ["leases", "nodes", "pods", "services", "endpoints"]
    verbs: ["get", "list", "update", "delete", "create", "watch"]

---
# rbac role binding to service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: glasnosticd
subjects:
  - kind: ServiceAccount
    name: glasnosticd # ServiceAccount name
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: glasnosticd # rbac role definition name
  apiGroup: rbac.authorization.k8s.io