---
apiVersion: v1
kind: Service
metadata:
  name: lookup-server
  namespace: glasnostic-system
  labels:
    {{- include "glasnosticd.labels" . | nindent 4 }}
spec:
  ports:
  - name: glasnostic-lookup-endpoint
    port: 9091
  selector:
    app: glasnosticd
---
apiVersion: v1
kind: Service
metadata:
  name: glasnosticd
  namespace: glasnostic-system
  labels:
    {{- include "glasnosticd.labels" . | nindent 4 }}
spec:
  ports:
  - name: injector-webhook
    port: 443
  - name: config-grpc
    port: 15010
  selector:
    app: glasnosticd
