apiVersion: v1
kind: Service
metadata:
  name: lookup-server
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "glasnostic.labels" . | nindent 4 }}
spec:
  ports:
    - name: glasnostic-lookup-endpoint
      port: 9091
  selector:
    {{- include "glasnostic.selectorLabels" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: glasnosticd
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "glasnostic.labels" . | nindent 4 }}
spec:
  ports:
    - name: injector-webhook
      port: 443
    - name: config-grpc
      port: 15010
  selector:
    {{- include "glasnostic.selectorLabels" . | nindent 6 }}
