{{ $tls := fromYaml ( include "glasnostic.gen-certs" . ) }}
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
apiVersion: admissionregistration.k8s.io/v1
{{- else }}
apiVersion: admissionregistration.k8s.io/v1beta1
{{- end }}
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "glasnostic.fullname" . }}-sidecar-injector
  {{- if .Values.certManager.enabled }}
  annotations:
    certmanager.k8s.io/inject-ca-from: {{ printf "%s/%s-admission" .Release.Namespace (include "glasnostic.fullname" .) | quote }}
    cert-manager.io/inject-ca-from: {{ printf "%s/%s-admission" .Release.Namespace (include "glasnostic.fullname" .) | quote }}
  {{- end }}
webhooks:
- name: sidecar-injector.glasnostic.com
  namespaceSelector:
    matchExpressions:
    - key: glasnostic
      operator: NotIn
      values: [ "disable" ]
  sideEffects: None
  clientConfig:
    {{- if not .Values.certManager.enabled }}
    caBundle: {{ $tls.caCert }}
    {{- end }}
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "glasnostic.fullname" . }}-glasnosticd
      path: /inject
  failurePolicy: Fail
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  admissionReviewVersions:
  - v1
  - v1beta1
{{- if not .Values.certManager.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glasnostic.fullname" . }}-admission
  namespace: {{ include "glasnostic.fullname" . }}-system
type: kubernetes.io/tls
data:
  ca.crt: {{ $tls.caCert }}
  tls.crt: {{ $tls.clientCert }}
  tls.key: {{ $tls.clientKey }}
{{- end }}