{{ $tls := fromYaml ( include "glasnosticd.gen-certs" . ) }}
---
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
apiVersion: admissionregistration.k8s.io/v1
{{- else }}
apiVersion: admissionregistration.k8s.io/v1beta1
{{- end }}
kind: MutatingWebhookConfiguration
metadata:
  name: glasnostic-sidecar-injector
webhooks:
- name: sidecar-injector.glasnostic.com
  namespaceSelector:
    matchExpressions:
    - key: glasnostic
      operator: NotIn
      values: [ "disable" ]
  sideEffects: None
  clientConfig:
    caBundle: {{ $tls.caCert }}
    service:
      namespace: {{ .Values.namespace }}
      name: glasnosticd
      path: /inject
  failurePolicy: Fail
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  admissionReviewVersions:
  - v1
  - v1beta1

---
apiVersion: v1
kind: Secret
metadata:
  name: injection-secret
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $tls.caCert }}
  tls.crt: {{ $tls.clientCert }}
  tls.key: {{ $tls.clientKey }}