{{- if not .Values.deploymentMode.daemonset -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "glasnosticd.fullname" . }}
  labels:
    {{- include "glasnosticd.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "glasnosticd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/webhook.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "glasnosticd.selectorLabels" . | nindent 8 }}
    spec:
      replicas: 1 # Needs to be fixed for now.
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "glasnosticd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: injection-secret
        secret:
          secretName: injection-secret
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:v{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - mountPath: "/etc/glasnostic"
          name: injection-secret
          readOnly: true
        envFrom:
          - configMapRef:
              name: {{ include "glasnosticd.fullname" . }}-config
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: INJECT_CERT_PATH
          value: "/etc/glasnostic/tls.crt"
        - name: INJECT_KEY_PATH
          value: "/etc/glasnostic/tls.key"
        - name: SIDECAR_IMAGE
          value: "{{ .Values.sidecar.repository }}:v{{ .Values.image.tag | default .Chart.AppVersion }}"
        - name: NODE_PORT
          value: {{ .Values.nodePort | quote }}
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: GLASNOSTICD_AS_DEPLOYMENT
          value: "true"
        resources:
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        ports:
        - name: exchange
          containerPort: 40753
          hostPort: {{ .Values.nodePort }}
        - name: service-port
          containerPort: 9091
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
{{- end -}}