{{ $tls := fromYaml ( include "glasnosticd.gen-certs" . ) }}
{{- if not .Values.certManager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: injection-secret
type: kubernetes.io/tls
data:
  tls.crt: {{ $tls.clientCert }}
  tls.key: {{ $tls.clientKey }}
---
{{- end }}

{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
apiVersion: admissionregistration.k8s.io/v1
{{- else }}
apiVersion: admissionregistration.k8s.io/v1beta1
{{- end }}
kind: MutatingWebhookConfiguration
metadata:
  name: glasnostic-sidecar-injector
  {{- if .Values.certManager.enabled }}
  annotations:
    certmanager.k8s.io/inject-ca-from: {{ printf "%s/%s-admission" .Release.Namespace (include "glasnosticd.fullname" .) | quote }}
    cert-manager.io/inject-ca-from: {{ printf "%s/%s-admission" .Release.Namespace (include "glasnosticd.fullname" .) | quote }}
  {{- end }}
webhooks:
- name: sidecar-injector.glasnostic.com
  namespaceSelector:
    matchExpressions:
    - key: glasnostic
      operator: In
      values: [ "enable" ]
  sideEffects: None
  clientConfig:
    {{- if not .Values.certManager.enabled }}
    caBundle: {{ $tls.caCert }}
    {{- else if .Values.certManager.caCert }}
    caBundle: {{ .Values.certManager.caCert }}
    {{- end }}
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "glasnosticd.fullname" . }}
      path: /inject
  failurePolicy: Fail
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  admissionReviewVersions:
  - v1
  - v1beta1
