repositoryID: 9eda0b1f-1b9e-40fb-adde-9f5dff19c655
owners: # (optional, used to claim repository ownership)
  - name: Christoph Kassen
    email: christoph@glasnostic.com
  - name: Tobias Kunze
    email: tobias@glasnostic.com