apiVersion: v1
name: glasnosticd
version: 0.5.1
appVersion: 1.12.2
description: Glasnostic Kubernetes Data Plane
type: application
home: https://glasnostic.github.io/helm-charts
icon: https://avatars.githubusercontent.com/u/6260715?s=200&v=4
keywords:
- glasnostic
maintainers:
- email: christoph@glasnostic.com
  name: ckassen
sources:
- https://github.com/glasnostic/helm-charts
kubeVersion: ">=1.16.0-0"
