apiVersion: v2
name: glasnosticd
version: 0.3.5
appVersion: 1.12.1
description: Glasnostic Kubernetes Data Plane
type: application
home: https://glasnostic.github.io/helm-charts
icon: https://raw.githubusercontent.com/glasnostic/helm-charts/master/docs/logo/glasnostic.png
keywords:
- glasnostic
maintainers:
- email: christoph@glasnostic.com
  name: ckassen
sources:
- https://github.com/glasnostic/helm-charts
kubeVersion: ">=1.16.0-0"
