# Default values for Glasnostic Kubernetes Data Plane.
# This is a YAML-formatted file.

# Glasnostic Network ID - The network ID of the network to use for the dataplane.
# Go to https://app.glasnostic.com/ to see the network ID.
networkKey: ""

# NodePort that Glasnostic will use. Change only when port is already in use.
nodePort: 40753

image:
  repository: public.ecr.aws/glasnostic/glasnosticd
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.12.1"

sidecar:
  repository: public.ecr.aws/glasnostic/sidecar
  # TODO: Christoph: remove next line if not used:
  pullPolicy: IfNotPresent
  tag: "v1.12.1"

certManager:
  # Use cert manager for webhook certs?
  enabled: false
  # issuerRef:
  #   name: glasnostic-ca
  #   kind: ClusterIssuer

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
 # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # runAsUser: 1001
  # fsGroup: 2000

resources:
  limits:
    cpu: 800m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 200Mi

nodeSelector: {}

tolerations: []

affinity: {}
